### ISSUE TITLE
Link outs to One Codex analysis pages

### ISSUE THREAD

**Issue by bcamarda** [onecodex/onecodex#137]
We need this to work with `target="_blank"`. This may require an update to JupyterLab?

**Comment by polyatail** [comment]
To clarify the issue, when users click elements in one of the interactive viz plots, we want them to be taken to some other page with more information. For example, points in a scatter plot that are samples should link to the classification results. Setting these links up is no problem, but they open in the current browser window with no easy way to change that.

I spent some time on this issue today. Earlier this year, someone requested that Vega add support (see [here](https://github.com/vega/vega/issues/1171)) for setting target, which they did. The problem is, this parameter is exposed only on vega.loader(), which is itself called by vegaEmbed(), which is part of python module `vega` that facilitates rendering in Jupyter notebooks. It may be difficult to change target windows for links without forking one of these other packages.

JupyterLab uses a different Altair renderer which might make it easier to change this parameter, but I haven't looked into it yet. Though simple, this issue may wind up being more than 2 if it requires changing notebook software.

**Comment by polyatail** [comment]
I was able to solve this in instances of our notebooks by installing a fork of `ipyvega` that manually sets target=_blank in the Vega JS.

See https://github.com/onecodex/docker-onecodex-notebook/pull/14
See https://github.com/onecodex/ipyvega/tree/target-blank
