### ISSUE TITLE
Send exception message to Sentry any time we sys.exit(1)

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#153]
Currently, in code like this:

```
    except (ValidationError, UploadException, Exception) as e:
        # TODO: Some day improve specific other exception error messages, e.g., gzip CRC IOError
        sys.stderr.write('\nERROR: {}'.format(e))
        sys.stderr.write('\nPlease feel free to contact us for help at help@onecodex.com\n\n')
        sys.exit(1)
```

We lose valuable info to Sentry, making debugging errors harder. We should do a `sentry.captureException` call in spots like this and _perhaps_ revert our special `SystemExit` handling.

**Comment by boydgreenfield** [comment]
So we do send the message... but maybe the exception is more/equally useful? TBD.

**Comment by bcamarda** [comment]
See: https://sentry.onecodex.com/onecodex/one-codex-cli/issues/3009/?query=is:unresolved

**Comment by polyatail** [comment]
A couple things:

- Most times we're calling `sys.exit()`, we can and should probably be calling `ctx.exit()` since we're within a Click context.
- Other times we're calling `sys.exit()`, we completely handle the error and I think it's appropriate that we're making that call. They are mostly for authentication failures or permissions errors accessing `~/.onecodex`. I don't think Sentry needs to know about these. Given that, I think it's appropriate to revert the  `SystemExit` catch in the `@telemetry` decorator.
- There is only one time that we call `sys.exit` after catching an exception that we don't entirely handle: the one @boydgreenfield quoted above for `UploadError` or `Exception` while uploading a file. In this case, I think we should just let the exception happen, get reported to Sentry, and let the user see it. Any `ValidationError` raised in this case is pretty well handled, so those I think we should continue to call `sys.exit` after and not send to Sentry.

**Comment by boydgreenfield** [comment]
@polyatail I think it's still useful from a telemetry POV to get the `ValidationError` info, because we can't guarantee that our validators are always working properly. That said, this is kind of a moot point when we move to a proxy. We could send it as a message though, or categorize those types of issues within the Sentry web interface. Thoughts?
