### ISSUE TITLE
Add bash completion support

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#155]
This would be very fancy and nice. Probably not necessary to autocomplete IDs (too much), but autocompleting all of our, e.g., `scripts` commands would be slick.

**Comment by polyatail** [comment]
Seems like this might already exist be default with `click`--see [here](https://click.palletsprojects.com/en/5.x/bashcomplete/). Will look more into how to activate it.

**Comment by bcamarda** [comment]
Look into what other packages do to enable bash completion (and figure out documentation?)

**Comment by polyatail** [comment]
Bash completion requires each command to have its own script which tells it how to do tab completion. Some systems will have a `bash-completion` package installed, which provides such scripts for many common tools. These scripts are located in either `/usr/local/etc/bash_completion.d` or `/etc/bash_completion.d`. The default `.bash_profile` or `.bashrc` scripts on a system may or may not source completion scripts from this directory.

```
# mac
brew install bash-completion

# linux
apt-get install -y bash-completion
```

The polite way to enable completion for `onecodex` would be to insert our completion script into this directory, if it exists and is writeable. Otherwise, it's on the user to install that package and our completion script, or install it directly into their `.bash_profile`.

This can be accomplished by adding a short bit of code that's run post-install in `setup.py`. We might also add something to the documentation in case someone wants to add it to their own `.bash_profile`.
