### ISSUE TITLE
Add report generation function to be called from *within* a notebook

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#184]
- [X] Turn off serving of static content from `notebook-service`
- [X] Override 'Download as...' menu in `notebook/templates/notebook.html`
- [X] Turn off top menu CSS in `notebook/static/css/override.css` or elsewhere
- [X] Look at `notebook_report.py` entry into nbconvert
- [X] Add `onecodex` export path via `nbconvert.exporters` entrypoint

**Comment by polyatail** [comment]
Script `notebook_report.py` is a good starting point.

**Comment by polyatail** [comment]
This issue spans several repos:

**onecodex/onecodex**
- Added `onecodex.reports` which contains `PDFExporter` and `DocumentExporter` classes that will call Weasyprint, do some formatting, and then either let a user download a PDF or link to the One Codex Document portal.

**onecodex/ipyvega**
- Changed JS to store static renderings as `image/svg+xml` rather than low-resolution `image/png`
- In `vega.VegaBase.display`, the authors were calling `IPython.display.display` /again/, after it had already been called from inside jupyter notebook. This caused two output cells (one blank of type `text/plain` and one of `application/javascript`) to be stored in a notebook file. Additionally, in `ipyvega/src/index.ts`, the authors were inserting an /additional/ output cell containing a static image. In total, this wonderful package was turning a single notebook cell into three! For no reason! Now, only a single cell is output.

**onecodex/notebook-service**
- I added a few lines which will cause static images and CSS to be served from `notebook-service` on older versions of `docker-onecodex-notebook` (i.e., below v0.4.0). Newer versions will get static files from within their docker images.

**onecodex/docker-onecodex-notebook**
- A few lines in the Dockerfile add custom HTML and CSS to clean up the menu, removing unused and irrelevant items.
