### ISSUE TITLE
Distance matrices biased by sampling depth

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#291]
This is not a bug in the software, more a concern with the underlying data. Because we don't rarefy, distance matrices calculated using something like `plot_distance` cause otherwise similar samples to cluster by sequencing depth. Take the following set of samples:

<img width="550" alt="Screen Shot 2019-07-24 at 2 29 30 PM" src="https://user-images.githubusercontent.com/2334701/61818733-7617c800-ae1f-11e9-9fd4-1885f4494550.png">

While they all appear quite to have similar compositions, here is the corresponding heatmap of Bray-Curtis distance:

<img width="426" alt="Screenshot 2019-07-24 14 26 39" src="https://user-images.githubusercontent.com/2334701/61818680-57193600-ae1f-11e9-8c8a-9ae34c27a8de.png">

This shows a Bray-Curtis between some of the samples being effectively 1 (i.e. the samples share no taxa in common). This is because Bray-Curtis is being calculated on counts, so samples with a high readcount (e.g. > 1 million) are considered highly dissimilar to samples with a low readcount (< 100k), even if the samples have similar normalized compositions.

I think in a case like this we need to have an option to compute the distance matrix based on normalized counts. Whether we do this through subsampling the counts vectors or multiplying the normalized vectors by a constant to get back to counts is up for discussion. Note, this probably shouldn't be the _default_, but it should at least be available as an option for cases where you need to correct for extreme differences in sequencing depth.

**Comment by polyatail** [comment]
Bray-Curtis distance on normalized read counts is equivalent to 1/2 the manhattan (city block) distance. Isn't that weird? Allowing Bray-Curtis on normalized data is kind of like offering a 0.5 * manhattan option.

We can enable this but I feel like the chances of user error are higher. The example here (I believe) is a legitimate result from Bray-Curtis since there are far more counted organisms in some datasets versus the others, and that is being called out. Rather than being a case of bias I think this is a case of working as intended but not being the correct metric for what we're trying to compare, i.e., the community composition.

Thoughts? Is there a reason to use Bray-Curtis here rather than e.g., UniFrac?

**Comment by clausmith** [comment]
You're right in that this is working as intended, it's just not necessarily obvious what's going on and that the read depths are effectively what's driving the clustering. I think the main issue with UniFrac is that the tree we're using is missing accurate branch lengths, so the UniFrac numbers are all over the place and actually _less_ correct (see #148).

**Comment by boydgreenfield** [comment]
@clausmith @audy @polyatail What's most commonly done in the literature (by the folks who are _not_ rarifying their data)? If they're using raw counts, let's keep this. If they're normalizing, let's consider a _way_ to do that (but maybe not have it be the default).

**Comment by polyatail** [comment]
I'm a little biased here because in Figure 1B of <a href="https://elifesciences.org/articles/01202">this paper</a> from 2013, I did Bray-Curtis on normalized 16S read counts. We tried a few different beta diversity metrics and chose Bray-Curtis for no particular reason other than it provided separation along the axes we wanted. I have since come to appreciate that something like weighted UniFrac would have been _much_ better to present, even if the points on the plot looked a bit scattered. This is because UniFrac takes community composition and phylogenetic distances into account and is less sensitive to differences in sampling depth. In contrast, Bray-Curtis is basically just Manhattan distance when using normalized read counts, and it's not really clear what exactly it's saying when using non-normalized read counts.

**Comment by clausmith** [comment]
I think if we can get the tree fixed up so we get accurate Unifrac distances then I’m happy to switch that to be the default metric. I do think we still need to support Bray-Curtis due to its popularity, but we don’t necessarily need to worry about this issue unless the defaults we provide are leading people down the wrong path.

**Comment by audy** [comment]
I thought everyone was doing t-SNE now :P

I think it's fine to do Bray-Curtis on proportion of total reads at least
for clustering (see Figure 4
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531).
People argue about this a lot though.

I haven't tested it but if you rarefy an infinite number of times isn't it
the same as taking the proportion and multiplying it by the depth you
rarefied to?

-- 
*Disclaimer: This e-mail and any attachments may contain Protected Health 
Information (PHI) and/or other confidential information. If you are not the 
intended recipient, any disclosure, copying, distribution or use of any 
information contained herein is strictly prohibited. If you have received 
this transmission in error, please immediately notify the One Codex 
Security Team at security@onecodex.com <mailto:security@onecodex.com>, and 
destroy the original transmission and any attachments without reading or 
saving.*
