### ISSUE TITLE
Add method for generating exports in current format as app.onecodex.com UI

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#81]
We need a method that, given a list of samples, generates an export file in the existing format.

**Comment by polyatail** [comment]
I'd like to relocate the method`ocx.Classifications.to_otu()` to `ResultsDataFrame` and rename `to_biom()`. It already has `to_csv()` since it is a subclassed `pd.DataFrame`. Both these methods can then be added to `SampleCollection` where it will just call the appropriate function on the underlying `ResultsDataFrame`.

**Comment by boydgreenfield** [comment]
@polyatail I think this issue is actually asking for a method on the backend API to generate various mashups. We have an issue on the backend for tracking, so closing this as a `wontfix` until we have an implement that we can just hook into here.

**Comment by boydgreenfield** [comment]
Nevermind... this is just badly worded. I'm rewriting the issue name.

**Comment by polyatail** [comment]
This functionality is in the new `SampleCollection` object. When #164 is merged, this issue becomes adding CLI access to those methods.
